Install fonts and define typeface constants
chuck-adaptive/ui-kit-2022 pull request #39
Opened 2022-10-04 14:20 UTC by Honglin-Lu

1. Install two fonts (Roboto and Merriweather) through `npm install` and import them in `preview.ts` file and also put them in the peerDependency.
2. Design system tokens for typography goes under the typography field.

2022-10-05 12:04 UTC, wenfeng-xing commented on src/theme/typography.ts
> +
I am not sure if we need to create a theme only for typography, maybe we need to talk about it.

2022-10-05 12:42 UTC, wenfeng-xing commented on src/theme/typography.ts
> +export const typography = createTheme({
I am not sure if we need to create a theme only for typography, maybe we need to talk about it.

2022-10-06 13:17 UTC, tprince232 requested changes

2022-10-06 18:58 UTC, Honglin-Lu commented on package.json
> +    "@fontsource/roboto": "^4.5.8",
Solved through Slack communication

2022-10-06 18:58 UTC, Honglin-Lu commented on .storybook/preview.ts
> +import '@fontsource/merriweather/400.css';
Solved through Slack communication.

2022-10-06 19:02 UTC, tprince232 approved these changes

2022-10-06 19:06 UTC, merged